### ISSUE TITLE
Build a method to make interactive plots from results of `welcomeml.ml.TextClustering`

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#293]
As a data scientist, I would like to have a generic method to make interactive plots of the results of the class `welcomeml.ml.TextClustering`, so I can sanity check the cluster results and quickly visualise my models.

This is part of the Epic #221.

Tasks:

- [x] Investigate and decide on different packages for the task: e.g. streamlit.io, pyvis, bokeh. #303 
- [x] Build a first pass `wellcomeml.viz.visualise_clusters.py` and auxiliary methods with basic point plotting capability #305 
- [x] Allow the class to receive a list of objects, so we can visualise multiple clustering results, for different parameters #321
- [x] Add interactive to cluster plots, so I can hover over points and show some information about the points (e.g. text, points, cluster info) #309
- [x] Add tests #326 
- [x] Add example with EPMC Pubs dataset. #325
